---

- name: ensure locales is installed
  apt:
    name: locales
    state: present

- name: Ensure a locale exists
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locales }}"
  notify: set system default locale

- name: where to check for
  set_fact:
    check_locale: 'System Locale: LANG={{ default_locale }}'

- name: check default locale
  command: localectl status
  changed_when: check_locale in deflocale.stdout_lines|list
  register: deflocale
  notify: set system default locale
